CREATE OR REPLACE TABLE ANALYTICS.SALES (
    SALE_ID NUMBER(38,0) AUTOINCREMENT,
    CUSTOMER_ID NUMBER(38,0),
    SALE_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    AMOUNT NUMBER(12,2),
    PAYLOAD VARIANT
);

SELECT CUSTOMER_ID,
       PAYLOAD:channel::STRING AS CHANNEL,
       IFF(AMOUNT > 1000, 'BIG', 'SMALL') AS SIZE_BAND,
       DATEADD(day, -30, CURRENT_DATE()) AS WINDOW_START,
       ZEROIFNULL(AMOUNT) AS AMT
FROM ANALYTICS.SALES
WHERE SALE_TS >= DATEADD(day, -30, CURRENT_TIMESTAMP())
QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY SALE_TS DESC) = 1;

SELECT s.CUSTOMER_ID, f.value:sku::STRING AS SKU
FROM ANALYTICS.SALES s,
     LATERAL FLATTEN(input => s.PAYLOAD:items) f;

COPY INTO ANALYTICS.SALES FROM @RAW_STAGE/sales/ FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);

CREATE OR REPLACE STREAM ANALYTICS.SALES_STREAM ON TABLE ANALYTICS.SALES;

CREATE OR REPLACE TASK ANALYTICS.REFRESH_DAILY
  WAREHOUSE = ETL_WH
  SCHEDULE = 'USING CRON 0 2 * * * UTC'
AS
  INSERT INTO ANALYTICS.SALES_SUMMARY SELECT CUSTOMER_ID, SUM(AMOUNT) FROM ANALYTICS.SALES GROUP BY CUSTOMER_ID;
