CREATE OR REPLACE TABLE SALES.CUSTOMERS (
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    FULL_NAME VARCHAR NOT NULL,
    EMAIL VARCHAR,
    CREATED_AT TIMESTAMP_NTZ,
    PROFILE VARIANT
);

CREATE OR REPLACE TABLE SALES.ORDERS (
    ORDER_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    ORDER_DATE TIMESTAMP_NTZ NOT NULL,
    AMOUNT NUMBER(12,2) NOT NULL,
    STATUS VARCHAR(20)
);
