-- Customer tier from the semi-structured profile
SELECT CUSTOMER_ID, FULL_NAME,
       PROFILE:tier::STRING AS TIER,
       IFF(CUSTOMER_ID > 3, 'NEW', 'EARLY') AS COHORT
FROM SALES.CUSTOMERS;

-- Latest order per customer
SELECT CUSTOMER_ID, ORDER_ID, AMOUNT
FROM SALES.ORDERS
QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE DESC) = 1;
