-- Change capture, nightly clean-up and file load
CREATE OR REPLACE STREAM SALES.ORDERS_STREAM ON TABLE SALES.ORDERS;

CREATE OR REPLACE TASK SALES.CLOSE_STALE_ORDERS
  WAREHOUSE = ETL_WH
  SCHEDULE = 'USING CRON 0 2 * * * UTC'
AS
  UPDATE SALES.ORDERS SET STATUS = 'Closed'
  WHERE STATUS = 'Open' AND ORDER_DATE < DATEADD(day, -30, CURRENT_TIMESTAMP());

COPY INTO SALES.ORDERS FROM @RAW_STAGE/orders/ FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);
