from wishbridge.rules import apply_rules, detect


def rules_of(findings, fixed=None):
    return {f.rule for f in findings if fixed is None or f.fixed == fixed}


def test_schema_map_rewrites_two_part_names_only():
    sql = "SELECT * FROM dbo.Orders o JOIN [dbo].Customers c ON 1=1 JOIN other.dbo.X x ON 1=1"
    out, f = apply_rules(sql, {"dbo": "main.sales"}, "mssql")
    assert "FROM main.sales.Orders" in out
    assert "JOIN main.sales.Customers" in out
    assert "other.dbo.X" in out  # three-part name left alone
    assert "schema-map" in rules_of(f, fixed=True)


def test_fixes_do_not_touch_strings_or_comments():
    sql = "SELECT '[dbo].x WITH (NOLOCK)' AS s -- GETDATE()\nFROM t"
    out, f = apply_rules(sql, {"dbo": "main.s"}, "mssql")
    assert out == sql
    assert not rules_of(f, fixed=True)


def test_tsql_leftovers_are_fixed():
    sql = "SELECT [Order ID], GETDATE() FROM main.s.t WITH (NOLOCK)\nGO\n"
    out, f = apply_rules(sql, {}, "mssql")
    assert "`Order ID`" in out
    assert "CURRENT_TIMESTAMP()" in out
    assert "NOLOCK" not in out
    assert "GO" not in out
    assert {"bracket-identifier", "getdate", "nolock-hint", "go-separator"} <= rules_of(f, fixed=True)


def test_tsql_rules_skip_other_dialects():
    out, f = apply_rules("SELECT arr[idx] FROM t", {}, "snowflake")
    assert out == "SELECT arr[idx] FROM t"
    assert not f


def test_dangling_comment_is_moved():
    sql = "SELECT\n    YEAR(d) AS \n -- Monthly revenue\n Yr,\n    MONTH(d) AS Mth\nFROM t"
    out, f = apply_rules(sql, {}, "mssql")
    assert "AS Yr, -- Monthly revenue" in out
    assert "dangling-comment" in rules_of(f, fixed=True)


def test_detects_blockers():
    sql = """SELECT @@ROWCOUNT() AS n;
SELECT * INTO #tmp FROM t;
SELECT TOP 5 * FROM t;
-- FIXME: precision differs
"""
    f = detect(sql, "mssql")
    by_rule = {x.rule: x for x in f}
    assert by_rule["system-variable"].severity == "error" and by_rule["system-variable"].line == 1
    assert by_rule["temp-table"].line == 2
    assert by_rule["top-clause"].line == 3
    assert by_rule["transpiler-note"].message == "precision differs"
    assert "local-variable" not in by_rule  # @@ROWCOUNT is not double-reported


def test_schema_map_handles_backticked_names():
    out, _ = apply_rules("SELECT * FROM `dbo`.`Orders` AS o", {"dbo": "main.sales"}, "mssql")
    assert out == "SELECT * FROM main.sales.`Orders` AS o"


def test_detects_merge_into_alias():
    sql = ("MERGE INTO c\nUSING `dbo`.`Customers` AS c INNER JOIN v ON v.id = c.id\n"
           "ON v.x > 1 WHEN MATCHED THEN UPDATE SET c.a = 1;")
    f = [x for x in detect(sql, "mssql") if x.rule == "merge-into-alias"]
    assert len(f) == 1 and f[0].severity == "error" and f[0].line == 1 and "MERGE target c" in f[0].message
    ok = "MERGE INTO main.s.customers AS c USING src AS s ON c.id = s.id WHEN MATCHED THEN UPDATE SET c.a = s.a;"
    assert not [x for x in detect(ok, "mssql") if x.rule == "merge-into-alias"]


def test_benign_transpiler_notes_are_info():
    f = detect("SELECT 1 -- FIXME: T-SQL CURRENT_TIMESTAMP/GETDATE returns datetime with approximately 3.33 ms resolution\n", "mssql")
    assert [x.severity for x in f] == ["info"]


def test_backticked_temp_table_is_warning_not_error():
    f = detect("CREATE TEMPORARY TABLE `#cv` AS SELECT 1; DROP TABLE `#cv`;", "mssql")
    assert {x.rule for x in f} == {"temp-table-name"} and all(x.severity == "warning" for x in f)


def test_clean_databricks_sql_has_no_findings():
    sql = "CREATE TABLE main.s.t (id BIGINT GENERATED BY DEFAULT AS IDENTITY, v DECIMAL(19,4));\nSELECT * FROM main.s.t LIMIT 10;"
    out, f = apply_rules(sql, {"dbo": "main.s"}, "mssql")
    assert out == sql and f == []
