CREATE TABLE SALES.CUSTOMERS (
    CUSTOMER_ID INTEGER NOT NULL,
    FULL_NAME NVARCHAR(200) NOT NULL,
    EMAIL NVARCHAR(255),
    CREATED_AT TIMESTAMP
) DISTRIBUTE ON RANDOM;

CREATE TABLE SALES.ORDERS (
    ORDER_ID INTEGER NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    ORDER_DATE TIMESTAMP NOT NULL,
    AMOUNT NUMERIC(12,2) NOT NULL,
    STATUS VARCHAR(20)
) DISTRIBUTE ON (CUSTOMER_ID) ORGANIZE ON (ORDER_DATE);
