-- Customers with account age
SELECT CUSTOMER_ID, FULL_NAME, NVL(EMAIL, 'n/a') AS EMAIL, AGE(CREATED_AT) AS ACCOUNT_AGE
FROM SALES.CUSTOMERS;

-- Top three customers by spend
SELECT CUSTOMER_ID, SUM(AMOUNT) AS TOTAL
FROM SALES.ORDERS
WHERE STATUS <> 'Cancelled'
GROUP BY CUSTOMER_ID
ORDER BY TOTAL DESC
LIMIT 3;
