-- Nightly clean-up and housekeeping
UPDATE SALES.ORDERS SET STATUS = 'Closed'
WHERE STATUS = 'Open' AND ORDER_DATE < NOW() - INTERVAL '30 days';

GROOM TABLE SALES.ORDERS;
GENERATE STATISTICS ON SALES.ORDERS;
