CREATE MULTISET TABLE SALES.CUSTOMERS, NO FALLBACK (
    CUSTOMER_ID INTEGER NOT NULL,
    FULL_NAME VARCHAR(200) CHARACTER SET UNICODE NOT NULL,
    EMAIL VARCHAR(255),
    CREATED_AT TIMESTAMP(0)
) UNIQUE PRIMARY INDEX (CUSTOMER_ID);

CREATE MULTISET TABLE SALES.ORDERS, NO FALLBACK (
    ORDER_ID INTEGER NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    ORDER_DATE TIMESTAMP(0) NOT NULL,
    AMOUNT DECIMAL(12,2) NOT NULL,
    STATUS VARCHAR(20)
) PRIMARY INDEX (CUSTOMER_ID);

COLLECT STATISTICS ON SALES.ORDERS COLUMN (CUSTOMER_ID);
