-- Top three customers by spend
SEL TOP 3 c.CUSTOMER_ID, c.FULL_NAME, SUM(o.AMOUNT) AS TOTAL_SPEND
FROM SALES.CUSTOMERS c
INNER JOIN SALES.ORDERS o ON o.CUSTOMER_ID = c.CUSTOMER_ID
WHERE o.STATUS <> 'Cancelled'
GROUP BY 1, 2
ORDER BY 3 DESC;

-- Latest order per customer
SELECT CUSTOMER_ID, ORDER_ID, AMOUNT
FROM SALES.ORDERS
QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE DESC) = 1;
