.LOGON tdprod/etl_user,${TD_PASSWORD};

CREATE VOLATILE TABLE STALE_ORDERS AS (
  SEL ORDER_ID FROM SALES.ORDERS
  WHERE STATUS = 'Open' AND ORDER_DATE < CURRENT_TIMESTAMP - INTERVAL '30' DAY
) WITH DATA ON COMMIT PRESERVE ROWS;

UPDATE SALES.ORDERS SET STATUS = 'Closed'
WHERE ORDER_ID IN (SEL ORDER_ID FROM STALE_ORDERS);

.IF ERRORCODE <> 0 THEN .QUIT 8;
.LOGOFF;
.QUIT 0;
