CREATE TABLE HR.EMPLOYEES (
    EMP_ID NUMBER(10) PRIMARY KEY,
    FULL_NAME VARCHAR2(200) NOT NULL,
    HIRE_DATE DATE DEFAULT SYSDATE,
    SALARY NUMBER(12,2),
    DEPT_ID NUMBER(10),
    MANAGER_ID NUMBER(10)
);

CREATE SEQUENCE HR.EMP_SEQ START WITH 1000 INCREMENT BY 1;

SELECT EMP_ID, NVL(SALARY, 0) AS SALARY, DECODE(DEPT_ID, 10, 'SALES', 20, 'IT', 'OTHER') AS DEPT,
       TO_CHAR(HIRE_DATE, 'YYYY-MM-DD') AS HIRED, ROWNUM AS RN
FROM HR.EMPLOYEES
WHERE ROWNUM <= 10;

SELECT EMP_ID, FULL_NAME, LEVEL AS DEPTH
FROM HR.EMPLOYEES
START WITH MANAGER_ID IS NULL
CONNECT BY PRIOR EMP_ID = MANAGER_ID;

SELECT e.FULL_NAME, d.DEPT_NAME
FROM HR.EMPLOYEES e, HR.DEPARTMENTS d
WHERE e.DEPT_ID = d.DEPT_ID(+);

INSERT INTO HR.EMPLOYEES (EMP_ID, FULL_NAME, SALARY) VALUES (HR.EMP_SEQ.NEXTVAL, 'New Hire', 50000);

CREATE OR REPLACE PROCEDURE HR.RAISE_SALARY(p_dept IN NUMBER, p_pct IN NUMBER) AS
BEGIN
  UPDATE HR.EMPLOYEES SET SALARY = SALARY * (1 + p_pct / 100) WHERE DEPT_ID = p_dept;
  DBMS_OUTPUT.PUT_LINE('Updated ' || SQL%ROWCOUNT || ' rows');
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
