CREATE TABLE SALES.CUSTOMERS (
    CUSTOMER_ID NUMBER(10) NOT NULL,
    FULL_NAME VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(255),
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE SALES.ORDERS (
    ORDER_ID NUMBER(10) NOT NULL,
    CUSTOMER_ID NUMBER(10) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    AMOUNT NUMBER(12,2) NOT NULL,
    STATUS VARCHAR2(20)
);

CREATE SEQUENCE SALES.ORDER_SEQ START WITH 1000 INCREMENT BY 1;
