CREATE OR REPLACE PROCEDURE SALES.CLOSE_STALE_ORDERS(p_days IN NUMBER) AS
BEGIN
  UPDATE SALES.ORDERS
     SET STATUS = 'Closed'
   WHERE STATUS = 'Open'
     AND ORDER_DATE < SYSDATE - p_days;
  DBMS_OUTPUT.PUT_LINE('Closed ' || SQL%ROWCOUNT || ' orders');
  COMMIT;
END;
/
