CREATE TABLE dbo.Customers
(
    CustomerID INT NOT NULL,
    FullName NVARCHAR(200) NOT NULL,
    Email NVARCHAR(255) NULL,
    CreatedAt DATETIME2 NOT NULL
)
WITH (DISTRIBUTION = REPLICATE, CLUSTERED COLUMNSTORE INDEX);

CREATE TABLE dbo.Orders
(
    OrderID INT NOT NULL,
    CustomerID INT NOT NULL,
    OrderDate DATETIME2 NOT NULL,
    Amount DECIMAL(19,4) NOT NULL,
    Status VARCHAR(20) NULL
)
WITH (DISTRIBUTION = HASH(CustomerID), CLUSTERED COLUMNSTORE INDEX);
