CREATE
    TABLE dbo.Customers
    (
        CustomerID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
        FullName VARCHAR(200) NOT NULL,
        Email VARCHAR(255),
        CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
        -- FIXME: T-SQL CURRENT_TIMESTAMP/GETDATE returns datetime with approximately 3.33 ms resolution; Databricks CURRENT_TIMESTAMP() uses microsecond precision
    ) TBLPROPERTIES( 'delta.feature.allowColumnDefaults' = 'supported' );

CREATE
    TABLE dbo.Orders
    (
        OrderID BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
        CustomerID INT NOT NULL,
        OrderDate TIMESTAMP NOT NULL,
        Amount DECIMAL(19, 4) NOT NULL,
        Status VARCHAR(20)
    );